{% set name = "schemathesis" %}
{% set version = "3.29.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/schemathesis-{{ version }}.tar.gz
  sha256: a36fc7eddb90978a5afaf3b87978a7f4387ca81088fd995b9a2c79c5470b3e75

build:
  noarch: python
  entry_points:
    - schemathesis = schemathesis.cli:schemathesis
    - st = schemathesis.cli:schemathesis
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - hatchling
    - python >=3.8,<4.0
  run:
    - python >=3.8,<4.0
    - backoff >=2.1.2,<3.0
    - click >=7.0,<9.0
    - colorama >=0.4,<1.0
    - httpx >=0.22.0,<1.0
    - hypothesis >=6.84.3,<7
    - hypothesis-graphql >=0.11.0,<1
    - hypothesis-jsonschema >=0.23.1,<0.24
    - jsonschema >=4.18.0,<5.0
    - junit-xml >=1.9,<2.0
    - pyrate-limiter >=2.10,<4.0
    - pytest-subtests >=0.2.1,<0.8.0
    - pytest >=4.6.4,<9
    - pyyaml >=5.1,<7.0
    - requests >=2.22,<3
    - starlette >=0.13,<1
    - starlette-testclient >=0.4.1,<1
    - tomli-w >=1.0.0,<2.0
    - tomli >=2.0.1,<3.0
    - werkzeug >=0.16.0,<4
    - yarl >=1.5,<2.0

test:
  imports:
    - schemathesis
  commands:
    - pip check
    - schemathesis --help
    - st --help
  requires:
    - pip

about:
  home: https://github.com/schemathesis/schemathesis
  doc_url: https://schemathesis.readthedocs.io/
  summary: Property-based testing framework for Open API and GraphQL based apps
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - Stranger6667
    - thewchan
