{% set name = "schemathesis" %}
{% set version = "3.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/schemathesis-{{ version }}.tar.gz
  sha256: c3e998c77b66139cfcdda3948457e17b26fe07a354ba7f1a781e031f2b293b84

build:
  noarch: python
  entry_points:
    - schemathesis = schemathesis.cli:schemathesis
    - st = schemathesis.cli:schemathesis
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.8
    - python >=3.7
  run:
    - attrs >=19.2,<=21.4
    - backoff >=2.1.2,<3.0.0
    - click >=7.0,<9.0
    - colorama >=0.4,<0.5
    - curlify >=2.2.1,<3.0.0
    - hypothesis >=6.13.3,<7.0.0
    - hypothesis-jsonschema >=0.22.0,<0.23.0
    - hypothesis-graphql >=0.9.0,<0.10.0
    - importlib_metadata >=1.1,!=3.8,<5
    - jsonschema >=4.3.2,<5.0.0
    - junit-xml >=1.9,<2.0
    - pytest >4.6.4,<8
    - pytest-subtests >=0.2.1,<0.8.0
    - python >=3.7
    - pyyaml >=5.1,<7.0
    - requests >=2.22,<2.28.0
    - starlette >=0.13,<1
    - tomli >=2.0.1,<3.0.0
    - tomli-w >=1.0.0,<2.0.0
    - typing-extensions >=3.7,<5
    - werkzeug >=0.16.0,<2.2
    - yarl >=1.5,<2.0

test:
  imports:
    - schemathesis
  commands:
    - pip check
    - schemathesis --help
    - st --help
  requires:
    - pip

about:
  home: https://github.com/schemathesis/schemathesis
  doc_url: https://schemathesis.readthedocs.io/
  summary: Property-based testing framework for Open API and GraphQL based apps
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
