{% set name = "schemathesis" %}
{% set version = "3.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/schemathesis-{{ version }}.tar.gz
  sha256: b936e504722d6fd4dfb8b32bb275f25b7a0eff2589b674b6a789d332b215790a

build:
  noarch: python
  entry_points:
    - schemathesis = schemathesis.cli:schemathesis
    - st = schemathesis.cli:schemathesis
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - hatchling
    - python >=3.7,<4.0
  run:
    - attrs >=22.1
    - backoff >=2.1.2,<3.0.0
    - click >=7.0,<9.0
    - colorama >=0.4,<1.0
    - curlify >=2.2.1,<3.0
    - httpx >=0.22.0,<1.0
    - hypothesis >=6.13.3,<7.0.0
    - hypothesis-graphql >=0.9.0,<1
    - hypothesis-jsonschema >=0.22.0,<1
    - importlib_metadata >=1.1,!=3.8,<5
    - jsonschema >=4.3.2,<5.0.0
    - junit-xml >=1.9,<2.0
    - pytest >4.6.4,<8
    - pytest-subtests >=0.2.1,<0.8.0
    - python >=3.7,<4.0
    - pyyaml >=5.1,<7.0
    - requests >=2.22,<=2.28.1
    - starlette >=0.13,<1
    - starlette-testclient ==0.2.0
    - tomli >=2.0.1,<3.0
    - tomli-w >=1.0.0,<2.0
    - typing-extensions >=3.7,<5
    - werkzeug >=0.16.0,<=2.2.2
    - yarl >=1.5,<2.0

test:
  imports:
    - schemathesis
  commands:
    - pip check
    - schemathesis --help
    - st --help
  requires:
    - pip

about:
  home: https://github.com/schemathesis/schemathesis
  doc_url: https://schemathesis.readthedocs.io/
  summary: Property-based testing framework for Open API and GraphQL based apps
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - Stranger6667
    - thewchan
