{% set name = "schemathesis" %}
{% set version = "3.17.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/schemathesis-{{ version }}.tar.gz
  sha256: ba82f1e4c2113cdd420c269a23554ef9da1683f19d763d9255b8aef605deb977

build:
  noarch: python
  entry_points:
    - schemathesis = schemathesis.cli:schemathesis
    - st = schemathesis.cli:schemathesis
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.8
    - python >=3.7
  run:
    - attrs >=19.2,<=21.4
    - backoff >=2.1.2
    - click >=7.0,<9.0
    - colorama >=0.4
    - curlify >=2.2.1
    - hypothesis >=6.13.3
    - hypothesis-jsonschema >=0.22.0
    - hypothesis-graphql >=0.9.0
    - importlib_metadata >=1.1,!=3.8,<5
    - jsonschema >=4.3.2
    - junit-xml >=1.9
    - pytest >4.6.4,<8
    - pytest-subtests >=0.2.1,<0.8.0
    - python >=3.7
    - pyyaml >=5.1,<7.0
    - requests >=2.22,<2.28.0
    - starlette >=0.13,<1
    - tomli >=2.0.1
    - tomli-w >=1.0.0
    - typing-extensions >=3.7,<5
    - werkzeug >=0.16.0,<2.2
    - yarl >=1.5

test:
  imports:
    - schemathesis
  commands:
    - pip check
    - schemathesis --help
    - st --help
  requires:
    - pip

about:
  home: https://github.com/schemathesis/schemathesis
  doc_url: https://schemathesis.readthedocs.io/
  summary: Property-based testing framework for Open API and GraphQL based apps
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
