{% set name = "schemathesis" %}
{% set version = "3.19.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/schemathesis-{{ version }}.tar.gz
  sha256: 779575cd2a7eb7b61a47ea8dfcadd80de9c3cc740dd2941970a25fc849292c23

build:
  noarch: python
  entry_points:
    - schemathesis = schemathesis.cli:schemathesis
    - st = schemathesis.cli:schemathesis
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - hatchling
    - python >=3.7,<4.0
  run:
    - backoff >=2.1.2,<3.0.0
    - click >=7.0,<9.0
    - colorama >=0.4,<1.0
    - curlify >=2.2.1,<3.0
    - httpx >=0.22.0,<1.0
    - hypothesis >=6.13.3,<7.0.0
    - hypothesis-graphql >=0.9.0,<1
    - hypothesis-jsonschema >=0.22.1,<1
    - importlib_metadata >=1.1,!=3.8,<5
    - jsonschema >=4.3.2,<5.0.0
    - junit-xml >=1.9,<2.0
    - pyrate-limiter >=2.10,<3.0
    - pytest >4.6.4,<8
    - pytest-subtests >=0.2.1,<0.8.0
    - python >=3.7,<4.0
    - pyyaml >=5.1,<7.0
    - requests >=2.22,<2.29
    - starlette >=0.13,<1
    - starlette-testclient ==0.2.0
    - tomli >=2.0.1,<3.0
    - tomli-w >=1.0.0,<2.0
    - typing-extensions >=3.7,<5
    - werkzeug >=0.16.0,<=3
    - yarl >=1.5,<2.0

test:
  source_files:
    - test
    - test-corpus
  imports:
    - schemathesis
  commands:
    - pip check
    - schemathesis --help
    - st --help
    # Skip test suite for now; requires src folder
    # - pytest -vvv --capture=tee-sys test
    # - pytest -vvv --capture=tee-sys test-corpus
  requires:
    # - aiohttp >=3.8.3,<4.0
    # - fastapi >=0.86.0
    # - flask >=2.1.1,<3.0
    - pip
    # - pytest
    # - pytest-asyncio >=0.18.0,<1.0
    # - pytest-httpserver >=1.0,<2.0
    # - pytest-mock >=3.7.0,<4.0
    # - pytest-xdist >=2.5,<3.0
    # - strawberry-graphql >=0.109.0
    # - trustme >=0.9.0,<1.0

about:
  home: https://github.com/schemathesis/schemathesis
  doc_url: https://schemathesis.readthedocs.io/
  summary: Property-based testing framework for Open API and GraphQL based apps
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - Stranger6667
    - thewchan
